### ISSUE TITLE
Should Seshat implement JSR 363 with a first stable release?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/seshat#1]
At the moment Seshat refers to JSR 363. If a stable release gets published, is the intention to continue using JSR 363 or the stable/snapshot versions of JSR 385?

JCP published a list of compatible implementations:
https://jcp.org/aboutJava/communityprocess/implementations/jsr363/index.html

Given there are stable 1.x releases Indriya should be added to that list. And if Seshat intends to publish a similar JSR 363 implementation, it should also be added.

**Comment by desruisseaux** [comment]
The intent is to implement JSR 363 first, then upgrade to JSR 385 (stable release if available, snapshot otherwise) soon after that.

**Comment by keilw** [comment]
Ok, thanks. I asked PMO if the list above could be updated. Indriya 1.2 is already on MavenCentral and the 1.x branch used by a couple of libraries, therefore adding it seems like a good idea. If one of those "release"  repos also has a milestone release of Seshat for JSR 363, it could/should be added, too.

**Comment by keilw** [comment]
Keeping this open to track possible addition by the JCP PMO to the jcp.org page, otherwise the question is answered.

**Comment by desruisseaux** [comment]
Superseded by task #14 opened specifically for the upgrade to Units of Measurement API 2.0 (JSR 385).
