### ISSUE TITLE
Deploy Seshat on Maven central

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/seshat#13]
A release is tagged there: https://github.com/unitsofmeasurement/seshat/releases/tag/1.0

This release is only a JSR 363 implementation (upgrade to JSR 385 will be done in a future release, see issue #1), but JSR 363 implementation is still needed for now anyway until we upgraded GeoAPI to JSr 385 (it will take a while, I have to go through the Open Geospatial Consortium process of standardisation).

Can this 1.0 release be deployed on Maven Central?

**Comment by desruisseaux** [comment]
Please let me know if I should create a bintray account or if we should use sonatype - both are fine for me.

By the way, what it the process for upgrading the version reported in [implementations page](https://jcp.org/aboutJava/communityprocess/implementations/jsr363/index.html)? I would like to upgrade SIS version from 0.8 to 1.0 (everything else stay the same).

**Comment by keilw** [comment]
It goes from Bintray to Sonatype, at least I never did it the other way round for this or other JSRs. It is up to you, happy to have you join https://bintray.com/unitsofmeasurement if you have or create an account, otherwise I could do it if you can't.

**Comment by desruisseaux** [comment]
Thanks, I now have access to the "Settings" tab! The web page is still not showing, but I should be able to investigate and fix by myself now.

**Comment by keilw** [comment]
Do you need any extra Bintray access rights for that?

**Comment by desruisseaux** [comment]
Maybe not. After clicking on "Maven" I see a "Add a package" link. But before clicking on it I want to learn more about deployment with Bintray, in order to not pollute the `unitsofmeasurement ` space.

**Comment by keilw** [comment]
Ok, I'll create that. I also "polluted" the snapshot repo only with some intermediary Indriya artifacts over the weekend, but none of them will make it into the release repo, so that is not so much worrisome. I'll create a Sechat "package" in bintray. There (not in the MavenCentral/Artifactory, once it is there it could only be deleted by JFrog or Sonatype) any package can also be deleted if something was wrong. Why does the POM still say 1.0-SNAPSHOT btw, shouldn't it be 1.1-SNAPSHOT now?

**Comment by desruisseaux** [comment]
You are right, the pom.xml should be 1.1-SNAPSHOT. I will fix that now.

**Comment by keilw** [comment]
I also updated the badge in the readme as it got a 1.0 release it doesn't seem "experimental" any more ;-)

**Comment by keilw** [comment]
I created https://bintray.com/unitsofmeasurement/maven/tech.uom%3Aseshat. Even used a free image from Wikipedia. Not sure, if anybody has the time and talent to create something like a JDuchess version of Sechat? ;-) Until then I hope it does, but tell me if someone came up with another logo. Everyone is a member, Bintray has few roles, I believe every member should be able to create a new version, let me know if there are problems, then I could also make some of you admin who really want to use it.

**Comment by desruisseaux** [comment]
Uploaded to https://dl.bintray.com/unitsofmeasurement/maven/tech/uom/seshat/1.0/
If I did correctly, its look like this task is done.

However if I understood correctly, this is a bintray repository, not Maven Central. Not a big deal, it is okay like that too.

**Comment by desruisseaux** [comment]
Saw new downloads in the statistics page, so I presume that it worked.

**Comment by keilw** [comment]
Cool, did you also synchronize it with your Sonatype account or is it not permitted for "tech.uom" groupId?

**Comment by keilw** [comment]
I could also do that with the uom owner account if you like.

**Comment by desruisseaux** [comment]
I didn't knew that it was possible to synchronize with Sonatype. If you know how to do, that would be nice!

**Comment by keilw** [comment]
Actually first you have to get it into JCenter, do you see that link. I'll reopen this because it is on Bintray now, JCenter and MavenCentral are still 2 more steps to go O;-)

**Comment by keilw** [comment]
Please ensure you got "javadoc" and "sources" artifacts because otherwise MavenCentral will refuse it?

**Comment by desruisseaux** [comment]
Sources are missing. I will fix the issue and redeploy.

**Comment by desruisseaux** [comment]
Redeployed with sources and tested in a small dummy project.

**Comment by keilw** [comment]
I think this can also be closed now.
