### ISSUE TITLE
Replace Bintray/JCenter in Seshat build settings and docs

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/seshat#15]
- [x] Maven POM and settings.xml, see https://central.sonatype.org/pages/apache-maven.html
- [x] Project Settings: Update `CI_DEPLOY_PASSWORD` for Sonatype/OSSH
- [x] Remove links to Bintray from README or the Seshat site and where necessary document how to use the Sonatype SNAPSHOT repo instead

See https://github.com/unitsofmeasurement/uom-parent/issues/24

**Comment by desruisseaux** [comment]
I presume it requires resolution of issue #13 (deployment on Maven Central).

**Comment by keilw** [comment]
Yes, they seem related. It looks like Seshat has no SNAPSHOT repositories or links to JCenter (which seems to have a slightly longer grace period) but the builds and deployments should be changed to MavenCentral.

**Comment by desruisseaux** [comment]
Seshat previous distribution management was:

```xml
  <distributionManagement>
    <repository>
      <id>bintray-unitsofmeasurement-maven</id>
      <name>unitsofmeasurement-maven</name>
      <url>https://api.bintray.com/maven/unitsofmeasurement/maven/tech.uom:seshat/;publish=1</url>
    </repository>
  </distributionManagement>
```

The distribution management defined in `tech.uom:uom-parent2.1.1` is:

```xml
  <!-- Deployment to public servers -->
  <distributionManagement>
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
    <repository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
  </distributionManagement>
```

I presume that we just need to inherit above values, or does Seshat needs to set something different?

**Comment by keilw** [comment]
I just fixed the password (item 2 on the list)

**Comment by desruisseaux** [comment]
For completing this task I need to deploy Seshat somewhere, I presume on Maven central. I have not tried deployment to OSSRH yet, but I presume that I need credential. How do I get credential for executing `mvn deploy`, or is there an alternative process to follow?

**Comment by keilw** [comment]
I tried to sync Sechat 1.0 from Bintray (while it's still available) to MavenCentral but it seems it was missing ASC signing:
```
Last Sync Errors: Missing Signature: '/tech/uom/seshat/1.0/seshat-1.0.jar.asc' does not exist for 'seshat-1.0.jar'. Missing Signature: '/tech/uom/seshat/1.0/seshat-1.0-sources.jar.asc' does not exist for 'seshat-1.0-sources.jar'. Missing Signature: '/tech/uom/seshat/1.0/seshat-1.0.pom.asc' does not exist for 'seshat-1.0.pom'. Missing Signature: '/tech/uom/seshat/1.0/seshat-1.0-javadoc.jar.asc' does not exist for 'seshat-1.0-javadoc.jar'. Dropping existing partial staging repository.
```

**Comment by keilw** [comment]
So @desruisseaux  either I would have to sign those artifacts myself and deploy or sync them with the technical user or we would have to request a new user for Sonatype deployment, if you already have one there for other projects like SIS?

**Comment by desruisseaux** [comment]
I have a user for Sonatype deployment of Apache SIS. The userid is `desruisseaux`. Maybe it is possible to restrict to credential to the `seshat` artifact in `tech/uom` group? I should have no need to touch to other artifacts.

**Comment by keilw** [comment]
I don't think Sonatype can do that, but if you prefer to only deploy Sechat, no worries. Will try to request it in their JIRA.

**Comment by desruisseaux** [comment]
Alternatively I have no objection if you keep control on `tech.uom` namespace and deploy Seshat yourself, but the intent is to avoid bothering you…

**Comment by keilw** [comment]
No, it is not a big problem for me or Sonatype and makes it easier once you feel Seshat is ready to implement JSR 385 ;-)

**Comment by desruisseaux** [comment]
Seshat 1.0.1 deployed in staging repository:

https://oss.sonatype.org/content/repositories/techuom-1056/

I will wait a 2~3 days in case any issue is reported. If none, I will release that and update the web site.

**Comment by keilw** [comment]
Cool, was there a reason to skip 1.0, because as it was never synced from Bintray that'll be lost, but no problem if there are no downstream dependencies to the initial release. I can check the Nexus later, normally that is visible there immediately and the search might take up to a day.

**Comment by desruisseaux** [comment]
No strong reason. It is true that keeping the 1.0 version may be better. I can still do the change.

**Comment by keilw** [comment]
At least 1.0.1 if that is already on MavenCentral you cannot really undo that release, so while you could certainly add 1.0.0 if you want changing one to the other does not seem possible (unless e.g. someone had a legal reason to remove an entire library from there)

**Comment by desruisseaux** [comment]
I have not released 1.0.1 yet, it is only in the staging repository for evaluation before real release. I dropped it right now and created a new one:

https://oss.sonatype.org/content/repositories/techuom-1057/

I will wait 2~3 days again and if no issue is reported, I will release the above.

**Comment by keilw** [comment]
Then it's not too late.

**Comment by desruisseaux** [comment]
Yes I did the change in above staging repository.

**Comment by desruisseaux** [comment]
Deployed to Maven central.
