### ISSUE TITLE
CI build job?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/seshat#6]
Is there a CI build job for Seshat already?

Most UoM projects use Circle-CI, but if e.g. from the SIS background something else is preferred, why not.

**Comment by desruisseaux** [comment]
There is no Continuous Integration (CI) build yet. I'm neutral on whether it should have one (running the tests locally take less than 10 seconds for now). If a CI is considered wanted, I'm neutral about wether it should be Circle-CI or another one.

**Comment by keilw** [comment]
If Circle-CI was fine, that already knows the organization, so adding a repository is relatively easy. All it needs is a config.yml that matches the desired Maven build goals, and should deployment to a Snapshot repository (Bintray or Sonatype) be desired, also those post-build steps.
